services:
  - type: web
    name: reke-platform-api
    env: docker
    plan: free
    rootDir: platform_api
    dockerfilePath: Dockerfile
    envVars:
      - key: REKE_SECRET
        sync: false   # manually set
      - key: REKE_PRICE
        value: "0.001"

  - type: web
    name: reke-fake-generator
    env: docker
    plan: free
    rootDir: fake_generator
    dockerfilePath: Dockerfile
    envVars:
      - key: REKE_API_URL
        sync: false  # set after API deployment
      - key: REKE_SECRET
        sync: false  # must match API secret
      - key: REKE_ORIGIN
        value: "Fake AI Generator"

  - type: web
    name: reke-platform-ui
    env: docker
    plan: free
    rootDir: platform_ui
    dockerfilePath: Dockerfile
    envVars:
      - key: REKE_API_URL
        sync: false  # set after API deployment
